/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import java.io.File
import java.nio.file.Files
import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun appHasAGreeting() {
        val tmpDir = Files.createTempDirectory("tmp-kotlin-shell-").toFile()
        File(tmpDir, "test.txt").apply { writeText("") }
        val result = shell("ls", workingDir = tmpDir).out
        assertEquals("test.txt\n", result)
    }
}
